import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";



export const metadata: Metadata = {
  title: "Note App",
  description: "Generated by Notes Goat",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <Toaster toastOptions={{
          style:{textAlign:"center"}
        }}/>
      </body>
    </html>
  );
}
